---------------------------------------------
ValueError  Traceback (most recent call last)
~\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py in _update_chunk_length(self)
    695         try:
--> 696             self.chunk_left = int(line, 16)
    697         except ValueError:

ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

IncompleteReadTraceback (most recent call last)
~\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py in _error_catcher(self)
    435             try:
--> 436                 yield
    437 

~\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py in read_chunked(self, amt, decode_content)
    762             while True:
--> 763                 self._update_chunk_length()
    764                 if self.chunk_left == 0:

~\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py in _update_chunk_length(self)
    699             self.close()
--> 700             raise httplib.IncompleteRead(line)
    701 

IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

ProtocolErrorTraceback (most recent call last)
~\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py in generate()
    750                 try:
--> 751                     for chunk in self.raw.stream(chunk_size, decode_content=True):
    752                         yield chunk

~\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py in stream(self, amt, decode_content)
    570         if self.chunked and self.supports_chunked_reads():
--> 571             for line in self.read_chunked(amt, decode_content=decode_content):
    572                 yield line

~\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py in read_chunked(self, amt, decode_content)
    791             if self._original_response:
--> 792                 self._original_response.close()
    793 

~\AppData\Local\Programs\Python\Python36\lib\contextlib.py in __exit__(self, type, value, traceback)
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:

~\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\response.py in _error_catcher(self)
    453                 # This includes IncompleteRead.
--> 454                 raise ProtocolError("Connection broken: %r" % e, e)
    455 

ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

ChunkedEncodingErrorTraceback (most recent call last)
<ipython-input-5-11a3e2319f69> in <module>
      1 reset_data()
      2 
----> 3 for i, resp in enumerate(response_stream):
      4 
      5     #Iteration Control ------------------------------------------

~\AppData\Local\Programs\Python\Python36\lib\site-packages\oandapyV20\oandapyV20.py in __stream_request(self, method, url, request_args, headers)
    255                                   headers=headers, stream=True)
    256         lines = response.iter_lines(ITER_LINES_CHUNKSIZE)
--> 257         for line in lines:
    258             if line:
    259                 data = json.loads(line.decode("utf-8"))

~\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py in iter_lines(self, chunk_size, decode_unicode, delimiter)
    793         pending = None
    794 
--> 795         for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
    796 
    797             if pending is not None:

~\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py in generate()
    752                         yield chunk
    753                 except ProtocolError as e:
--> 754                     raise ChunkedEncodingError(e)
    755                 except DecodeError as e:
    756                     raise ContentDecodingError(e)

ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))